---
title: "LinkedIn post analyzer"
output: html_notebook
---


Environment
```{r}
library(tidyverse)
```
```{r}

read.delim(file = "C:/Users/pmun/Downloads/pan")
data = readxl::read_xlsx("C:/Users/pmun/Downloads/Content_2023-08-10_2024-08-08_PatrickMunk.xlsx",
                         sheet = 2, skip = 2)

engagements = data[,1:3]
impressions = data[,5:7]
                         
colnames(engagements) = c("url","date","engagements")
colnames(impressions) = c("url","date","impressions")

dataAll = full_join(engagements, impressions) %>%
  mutate(engageRate = engagements / impressions * 100) %>%
  mutate(date = as.Date(date, format = "%m/%d/%Y"))

```
Data visualization
```{r}

dataAll %>% arrange(-engageRate) %>% ggplot(aes(engageRate)) + geom_histogram()

dataAll %>% arrange(-engageRate) %>% ggplot(aes(impressions, engagements)) + geom_point()


dataAll %>% arrange(-engageRate) %>% ggplot(aes(log10(impressions), log10(engagements), col = engageRate)) + geom_point()

dataAll %>% na.omit %>% ggplot(aes(date, engageRate, fill = engageRate)) + geom_bar(stat = "identity", position = "dodge")

dataAll %>% na.omit %>% ggplot(aes(date, engagements, fill = engageRate)) + geom_bar(stat = "identity")
```

